name: 'Setup IQ CLI'
description: 'setup-iq-cli action sets up the IQ CLI (jar) as a tool in GitHub, to be available to other actions'
author: 'Sonatype'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'shield'
  color: 'purple'

# Define your inputs here.
inputs:
  iq-cli-version:
    description: 'IQ CLI version to be used. Either this or `iq-cli-download-url` is required.'
    required: false
  iq-cli-download-url:
    description:
      'URL from where the IQ CLI jar file will be downloaded. Must be provided if `iq-cli-version` is not specified.'
    required: false

# Define your outputs here.
outputs:
  iq-cli-version:
    description: 'Semver valid version of the IQ CLI configured. It can be used as an input parameter for run-iq-cli.'

runs:
  using: node20
  main: dist/main/index.js
